name: CI

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust-version: [stable, beta, nightly]

    env:
      RUST: ${{ matrix.rust-version }}

    steps:
    - uses: actions/checkout@v3

    - run: rustup update ${{ matrix.rust-version }}
    - run: rustup default ${{ matrix.rust-version }}

    - id: cache-rust
      uses: Swatinem/rust-cache@v1
      with:
        key: v2

    - run: cargo install rustfilt coverage-prepare
      if: steps.cache-rust.outputs.cache-hit != 'true'

    - run: rustup component add llvm-tools-preview

    - run: cargo test --test test_date --test test_datetime --test test_time --test test_duration
      env:
        RUST_BACKTRACE: 1
        RUSTFLAGS: '-C instrument-coverage'

    - run: coverage-prepare lcov $(find target/debug/deps -regex '.*/test_[^.]*')

    - run: cargo test --doc

    - uses: codecov/codecov-action@v2
      with:
        env_vars: RUST


  bench:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update nightly
    - run: rustup default nightly
    - uses: Swatinem/rust-cache@v1

    - run: cargo bench

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: rustup update stable
    - run: rustup default stable
    - uses: Swatinem/rust-cache@v1

    - run: rustup component add rustfmt clippy

    - run: cargo fmt -- --check
    - run: cargo clippy

    - run: cargo doc
